### PR TITLE
Update auth api, add config file, add rotation

### PR DESCRIPTION
**Pull request by amenekowo**
Add config file at `/etc/pihole-dashboard/config.toml` for set eth interface, webui port, api key and different orientation

### CODE REVIEW

**Comment by santoru** [comment]
Hey, thank you for contributing 😄 I will test the changes in the following days and comment/merge.

**Comment by amenekowo** [comment]
You're welcome😄
By the way, I tested my updated version on my rpi 4b, running for a day without problem. I don't test "remote server" function though, because I run pi-hole on my pi.

于 2023年1月23日 GMT+08:00 下午6:44:28, Alessio Santoru ***@***.***> 写到:

**Comment by OWReaper** [comment]
I was wondering if anyone can help me out.
I am stuck with a waveshare but V3 I can run the wave share test and it works fine for v3.
when I run the command sudo pihole-dashboard-draw I keep receiving API Response: []

I have no clue what that is refering to other than API token is my best guess.

I used Amenekowo's fork as well and added the api ky in the toml file but still getting the same result.

I even found the v2 entires (found 2 of them) in the __init__.py and changed them to the v3 and still can not get past that error.

Please assist with API Response: [] error.

Thank you,
Reaper

**Comment by amenekowo** [comment]
Hi @OWReaper , I just got my V3 screen, but my build for pihole moved to another computer so I can't test these now. I will get a pi to test it out and try to fix it later :)

**Comment by OWReaper** [comment]
> Hi @OWReaper , I just got my V3 screen, but my build for pihole moved to another computer so I can't test these now. I will get a pi to test it out and try to fix it later :)

Man I greatly appreciate it. I can adjust code but running in nano or Linux for that matter is a steep learning curve. Thank you for help me out on this.

**Review by santoru — APPROVED** [review]
Looks good. Thank you for the contribution. Let me know if we can merge this.

**Comment by amenekowo** [comment]
Of course. I am still learning English so feel free to change anything not fluent in README :)

**Comment by amenekowo** [comment]
@santoru I think we can merge for now if we don't need some new features.

**Pull request merged**
